adminUser:
  password: vault:eks-tf-cluster5/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  email: dgozalo@cloudbees.com
  token: vault:eks-tf-cluster5/pipelineUser:token
  username: dgozalo
prow:
  hmacToken: vault:eks-tf-cluster5/prow:hmacToken
